@PokedexApiGraphQL_HostAddress = http://localhost:5192

GET {{PokedexApiGraphQL_HostAddress}}/todos/
Accept: application/json

###

GET {{PokedexApiGraphQL_HostAddress}}/todos/1
Accept: application/json

###
